apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: kafka-connect-example
deploy:
  helm:
    releases:
      - name: debezium-postgres
        chartPath: charts/debezium-postgres
        setValues:
          image.tag: "14"
          env.POSTGRES_PASSWORD: "123"
          env.POSTGRES_USER: "postgres"
          env.POSTGRES_DB: "cdc-using-debezium"
      
      - name: debezium-connect
        chartPath: charts/debezium-connect
        namespace: default  # 名前空間を確認
        setValues:
          image.tag: "2.4"
          env.BOOTSTRAP_SERVERS: "kafka-dev-controller-0.kafka-dev-controller-headless.default.svc.cluster.local:9092"  # サービス名とポートを確認
          env.GROUP_ID: "1"
          env.CONFIG_STORAGE_TOPIC: "my_connect_configs"
          env.OFFSET_STORAGE_TOPIC: "my_connect_offsets"
          env.STATUS_STORAGE_TOPIC: "my_connect_statuses"
          env.ENABLE_DEBEZIUM_SCRIPTING: "true"
          extraEnv.CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
          extraEnv.CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
          extraEnv.CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
          extraEnv.CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
          extraEnv.CONNECT_REST_ADVERTISED_HOST_NAME: "debezium-connect"
          extraEnv.CONNECT_GROUP_ID: "1"
          extraEnv.CONNECT_CONFIG_STORAGE_TOPIC: "my_connect_configs"
          extraEnv.CONNECT_OFFSET_STORAGE_TOPIC: "my_connect_offsets"
          extraEnv.CONNECT_STATUS_STORAGE_TOPIC: "my_connect_statuses"
          extraEnv.CONFIG_STORAGE_REPLICATION_FACTOR: "1"
          extraEnv.OFFSET_STORAGE_REPLICATION_FACTOR: "1"
          extraEnv.STATUS_STORAGE_REPLICATION_FACTOR: "1"
          service:
            type: ClusterIP
            ports:
              - port: 8083
                targetPort: 8083
                protocol: TCP

      - name: kafka
        chartPath: charts/kafka
        namespace: default  # 名前空間を確認
        setValues:
          service.type: ClusterIP
          persistence.enabled: true
          persistence.size: 8Gi
          zookeeper.enabled: false

profiles:
  - name: dev
    deploy:
      helm:
        releases:
          - name: debezium-postgres-dev
            chartPath: charts/debezium-postgres
            namespace: default  # 名前空間を確認
            setValues:
              image.tag: "14"
              env.POSTGRES_PASSWORD: "123"
              env.POSTGRES_USER: "postgres"
              env.POSTGRES_DB: "cdc-using-debezium"
          
          - name: debezium-connect-dev
            chartPath: charts/debezium-connect
            namespace: default  # 名前空間を確認
            setValues:
              image.tag: "2.4"
              env.BOOTSTRAP_SERVERS: "kafka-dev-controller-0.kafka-dev-controller-headless.default.svc.cluster.local:9092"  # サービス名とポートを確認
              env.GROUP_ID: "1"
              env.CONFIG_STORAGE_TOPIC: "my_connect_configs"
              env.OFFSET_STORAGE_TOPIC: "my_connect_offsets"
              env.STATUS_STORAGE_TOPIC: "my_connect_statuses"
              env.ENABLE_DEBEZIUM_SCRIPTING: "true"
              extraEnv.CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
              extraEnv.CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
              extraEnv.CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
              extraEnv.CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
              extraEnv.CONNECT_REST_ADVERTISED_HOST_NAME: "debezium-connect"
              extraEnv.CONNECT_GROUP_ID: "1"
              extraEnv.CONNECT_CONFIG_STORAGE_TOPIC: "my_connect_configs"
              extraEnv.CONNECT_OFFSET_STORAGE_TOPIC: "my_connect_offsets"
              extraEnv.CONNECT_STATUS_STORAGE_TOPIC: "my_connect_statuses"
              extraEnv.CONFIG_STORAGE_REPLICATION_FACTOR: "1"
              extraEnv.OFFSET_STORAGE_REPLICATION_FACTOR: "1"
              extraEnv.STATUS_STORAGE_REPLICATION_FACTOR: "1"

          - name: kafka-dev
            chartPath: charts/kafka
            namespace: default  # 名前空間を確認
            setValues:
              service.type: ClusterIP
              persistence.enabled: true
              persistence.size: 8Gi
              zookeeper.enabled: false
