apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium-postgres
  template:
    metadata:
      labels:
        app: debezium-postgres
    spec:
      containers:
        - name: postgres
          image: debezium/postgres:14
          env:
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.env.POSTGRES_PASSWORD }}"
            - name: POSTGRES_USER
              value: "{{ .Values.env.POSTGRES_USER }}"
            - name: POSTGRES_DB
              value: "{{ .Values.env.POSTGRES_DB }}"
          ports:
            - containerPort: 5432