env:
  BOOTSTRAP_SERVERS: "kafka-dev.default.svc.cluster.local:9092"  # Check the service name and port
  GROUP_ID: "1"
  CONFIG_STORAGE_TOPIC: "my_connect_configs"
  OFFSET_STORAGE_TOPIC: "my_connect_offsets"
  STATUS_STORAGE_TOPIC: "my_connect_statuses"
  ENABLE_DEBEZIUM_SCRIPTING: "true"
  CONFIG_STORAGE_REPLICATION_FACTOR: "1"
  OFFSET_STORAGE_REPLICATION_FACTOR: "1"
  STATUS_STORAGE_REPLICATION_FACTOR: "1"
extraEnv:
  CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_REST_ADVERTISED_HOST_NAME: "debezium-connect"
  CONNECT_GROUP_ID: "1"
  CONNECT_CONFIG_STORAGE_TOPIC: "my_connect_configs"
  CONNECT_OFFSET_STORAGE_TOPIC: "my_connect_offsets"
  CONNECT_STATUS_STORAGE_TOPIC: "my_connect_statuses"